// TASK ACTIONS
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const FETCH_TASKS = "FETCH_TASKS";
export const EDIT_TASK = "EDIT_TASK";
export const CHECK_TASK_DONE = "CHECK_TASK_DONE";

// CATEGORY ACTIONS
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
