// TASK ACTIONS
export const TASK_ACTION_TYPES = {
  ADD_TASK: "ADD_TASK",
  DELETE_TASK: "DELETE_TASK",
  FETCH_TASKS: "FETCH_TASKS",
  EDIT_TASK: "EDIT_TASK",
  CHECK_TASK_DONE: "CHECK_TASK_DONE"
};

// CATEGORY ACTIONS
export const CATEGORY_ACTION_TYPES = {
  ADD_CATEGORY: "ADD_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY"
};
